ifndef W2C2_DIR
	$(error set W2C2_DIR to the directory containing w2c2)
endif

W2C2 ?= $(W2C2_DIR)/w2c2/w2c2
CFLAGS = -O0 -g -I$(W2C2_DIR)/w2c2
LDFLAGS += -framework AppKit
FRAMEWORKS = objc Foundation AppKit

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

%.o: %.m
	$(CC) $(CFLAGS) -c -o $@ $<

bridge_%.o: ../Bridge/10_4/%.m
	$(CC) $(CFLAGS) -c -o $@ $<

app: app.o main.o $(foreach framework,$(FRAMEWORKS),bridge_$(framework).o)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

.PHONY: clean
clean:
	rm -rf *.o app
